// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmgkxlosikgjodoipnzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtZ2t4bG9zaWtnam9kb2lwbnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTA5NTAsImV4cCI6MjA1OTE2Njk1MH0.8wXg_Ij9rsL3cY-sHyYs5v-5ngMD2ScchLK56OUBGEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);